### ISSUE TITLE
Generate serialization code for unions.

### ISSUE THREAD

**Issue by mkochanowicz** [itwasntme-mk/serialize3#2]
1. Only SERIALIZABLE_OBJECT or manual serialization should be allowed.
1. For SERIALIZABLE_OBJECT only trivial auto-serialized member types allowed (POD types or other SERIALIZABLE_OBJECT class/struct/union).
1. Should be serialized only one member with biggest sizeof.

**Comment by itwasntme-mk** [comment]
Done: 3e9c4fca977075c5d17b2125acef3ba213c667bc
